### ISSUE TITLE
Using Actions

### ISSUE THREAD

**Issue by Bingdom** [uraimo/run-on-arch-action#111]
Hello,

I was wondering if there was a way to use actions?

Currently my situation is to use Python under debian. Python cannot be installed directly from debian which means I have to compile it myself.
I've tried building python, but it's not ideal and takes a very long time.

I'm quite new to GitHub Actions, so I'm not sure of the best way it could be implemented?

**Comment by martin-g** [comment]
Hi! It is not clear what exactly you ask and want to do.
run-on-arch-action is an Github Action! So, I guess the answer to your question is YES.

**Comment by Bingdom** [comment]
Ok sorry, I'll try to be more clear-

Essentially I want to run Python under aarch64 with Debian.

While yes this action does let you run commands under the distro/architecture, there appears to not have a method to be able to run GitHub actions from within this action.

So all this caching stuff I'd have to do manually (like caching pip) from my understanding.

My ultimate goal is to compile my python project under various different architectures/distributions

**Comment by martin-g** [comment]
It is more clear now!
No, this action cannot execute inner actions.
For that you can use self-hosted runners. For example you can get a free Linux ARM64 VM from Oracle Cloud and setup a self-hosted runner on it. The extra bonus is that it will be much faster than QEMU emulation.
But I don't think Oracle Cloud provides Debian images... They have Ubuntu.

**Comment by uraimo** [comment]
@Bingdom as Martin said, if you add additional steps after run-on-arch those will run on host, outside the emulated architecture that you wanted. All the things you want to do needs to be inside the `run` section.
