### ISSUE TITLE
feature request: Firecracker VM support

### ISSUE THREAD

**Issue by uhthomas** [uraimo/run-on-arch-action#115]
It would be really nice to support [Firecracker](https://github.com/firecracker-microvm/firecracker) in addition to QEMU. The startup time should be much quicker.

**Comment by martin-g** [comment]
https://github.com/firecracker-microvm/firecracker/blob/main/FAQ.md#can-i-emulate-a-different-architecture-in-the-guest-than-the-one-on-the-host
