### ISSUE TITLE
/root/run-on-arch-install.sh: not found

### ISSUE THREAD

**Issue by Slackadays** [uraimo/run-on-arch-action#120]
I'm trying to add tons of new actions to my project CB to get more testing done. However, my action keeps getting this error of not being able to find the script:
```
Status: Downloaded newer image for arm64v8/ubuntu:20.04
   ---> 758cd4ebb217
  Step 2/3 : COPY ./run-on-arch-install.sh /root/run-on-arch-install.sh
   ---> 297bfd98a834
  Step 3/3 : RUN chmod +x /root/run-on-arch-install.sh && /root/run-on-arch-install.sh
  Warning: rning] The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
   ---> Running in 8227fec71c4d
  /bin/sh: 1: /root/run-on-arch-install.sh: not found
  The command '/bin/sh -c chmod +x /root/run-on-arch-install.sh && /root/run-on-arch-install.sh' returned a non-zero code: 127
  Error: The process '/home/runner/work/_actions/uraimo/run-on-arch-action/v2/src/run-on-arch.sh' failed with exit code 127
```
You can find this action here: https://github.com/Slackadays/Clipboard/blob/7c79526035e4a5e059841964c846342c6b240cfa/.github/workflows/test-clipboard.yml#L103

And an example of the actions failing: https://github.com/Slackadays/Clipboard/actions/runs/4813348388

Is there something I'm missing?

**Comment by martin-g** [comment]
I'd try commenting out the `shell: ` and see whether it changes things.

Also move https://github.com/Slackadays/Clipboard/blob/7c79526035e4a5e059841964c846342c6b240cfa/.github/workflows/test-clipboard.yml#L130-L152 to `install: ...`

**Comment by Slackadays** [comment]
@martin-g Doing the suggested `install:` change yielded this: https://github.com/Slackadays/Clipboard/commit/d9a6b6b5d0bb8c9428362a4ae7e3649c82096001

The runs (after fixing a minor yaml error): https://github.com/Slackadays/Clipboard/actions/runs/4813668765

Still doesn't work :(

**Comment by Slackadays** [comment]
However, it looks like it's a different error this time, where `sudo` isn't getting found. So, it might be a different issue now.

**Comment by Slackadays** [comment]
The fix for that was to remove `sudo` from `sudo apt-get -y install...` in my build script, so now it works great and CB has 149 total GH Actions as a result :)

**Comment by uraimo** [comment]
@Slackadays Hi! sudo is not included in the default packages on the container most of the times, but you can install it if you ever need it.
