### ISSUE TITLE
Support for actions steps instead of just shell commands

### ISSUE THREAD

**Issue by sparr** [uraimo/run-on-arch-action#124]
I have a workflow that does `uses: actions/checkout@v3` (and many other workflows using many other stock and custom actions) and it seems that to run this workflow on a different arch using this action I would need to completely reimplement the checkout action as a shell script.

I don't know if it's possible or feasible, but it would be wonderful to be able to encapsulate other workflow steps within the environment provided by this action.

**Comment by uraimo** [comment]
Hi Spar, I agree that it would improve a lot the user experience but sadly it's not possible now and will never be, it would require to reimplement and handle workflows completely inside the context of the container created by this action, for multiple architectures, or pull of some hack at a higher level.
