### ISSUE TITLE
Need pinned Alpine Linux versions, e.g., v3.17

### ISSUE THREAD

**Issue by probonopd** [uraimo/run-on-arch-action#128]
Currently, only Alpine Linux "latest" is available which means that it is a moving target.

As a result, my once-working build all of a sudden broke without me having changed anything in my workflow.

Hence, we need non-changing Alpine Linux versions.

How can I pin Alpine Linux to e.g., v3.17?

**Comment by uraimo** [comment]
Hi, yes, now you can select your own image with the `base_image` option, [see the readme](https://github.com/uraimo/run-on-arch-action).
Set arch and distro to none and base_image to something like arm64v8/alpine:3.17.4

**Comment by probonopd** [comment]
Thank you very much @uraimo
