### ISSUE TITLE
No match for platform in manifest: not found

### ISSUE THREAD

**Issue by robertsLando** [uraimo/run-on-arch-action#150]
I keep getting this error now and I didn't changed anything on my repo that could cause this issue:

```
  ERROR: failed to solve: arm32v7/node:18-bookworm: failed to resolve source metadata for docker.io/arm32v7/node:18-bookworm: no match for platform in manifest: not found
```

Ref: https://github.com/zwave-js/zwave-js-ui/actions/runs/9628101644/job/26555958317#step:6:26

Could someone explain me why this isn't working anymore?

Previous successfull build: https://github.com/zwave-js/zwave-js-ui/actions/runs/9578017114/job/26407367969

**Comment by uraimo** [comment]
Did it run at least once? I see that you changed the debian release here: https://github.com/zwave-js/zwave-js-ui/commit/d66bcb9cff1e48bf6e6a95fdbcd411f3c4a9dfae

But 18-bookworm seems to be available on the docker hub https://hub.docker.com/r/arm32v7/node/ ,  here: https://github.com/nodejs/docker-node/blob/d3965ef329265accff145164f06653216e416685/18/bookworm/Dockerfile

Weird, docker is not able to resolve that arm32v7/node:18-bookworm image.

**Comment by robertsLando** [comment]
@uraimo that's a try I did but the problem is not the image not existing, is the arch (platform) doesn't match the target, at least that error errors means that (and not that the docker image doesn't exists at all) and it makes no sense to me as of course the gh action isn't arm32v7 but it never did, that's why I'm wondering what's going on here

**Comment by robertsLando** [comment]
news on this?

**Comment by martin-g** [comment]
Go to https://github.com/zwave-js/zwave-js-ui/actions/caches and remove all caches.
You may also want to address the warnings at https://github.com/zwave-js/zwave-js-ui/actions/runs/9853888762
```
 Build package and attach to release (18.x)
The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v3, actions/setup-node@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

```

**Comment by uraimo** [comment]
Thanks Martin.

Not actively looking into this. And I'm starting to consider closing every issue that includes the use of a custom image outside of the vanilla ones for major distributions. I simply have no time to debug individual docker issues, hope you will understand.

**Comment by uronito** [comment]
@robertsLando see this 

https://github.com/nodejs/docker-node/issues/2110

**Comment by robertsLando** [comment]
Thanks @uronito for the suggestion. This change fixed the issue:

```
          base_image: '--platform=linux/arm64 arm64v8/node:18-bullseye'
```

Dunno if it could be worth mentioning this on README.md @uraimo when using custom images.

Not needed to delete caches @martin-g but thanks anyway for the suggestion
