### ISSUE TITLE
no match for platform in manifest: not found

### ISSUE THREAD

**Issue by ChristopherRabotin** [uraimo/run-on-arch-action#154]
Hi there,

I use this action as part of my build process for a Python library. The build was passing fine [just five days ago](https://github.com/nyx-space/hifitime/actions/runs/11319337822/job/31475233075). However, [as of this evening](no match for platform in manifest: not found), I get the following error when using the action:

```
  #3 [auth] ppc64le/ubuntu:pull token for registry-1.docker.io
  #3 DONE 0.0s
  
  #2 [internal] load metadata for docker.io/ppc64le/ubuntu:22.04
  #2 ERROR: no match for platform in manifest: not found
  ------
   > [internal] load metadata for docker.io/ppc64le/ubuntu:22.04:
  ------
  Dockerfile.ppc64le.ubuntu22.04:1
  --------------------
     1 | >>> FROM ppc64le/ubuntu:22.04
     2 |     
     3 |     COPY ./run-on-arch-install.sh /root/run-on-arch-install.sh
  --------------------
  ERROR: failed to solve: ppc64le/ubuntu:22.04: failed to resolve source metadata for docker.io/ppc64le/ubuntu:22.04: no match for platform in manifest: not found
```

This comes at an inconvenient time because I noticed the error just as I was about to release the new stable version of my library. Any quick fix would be appreciated.

Thanks

**Comment by martin-g** [comment]
Please see https://github.com/uraimo/run-on-arch-action/issues/152#issuecomment-2401981347

**Comment by ChristopherRabotin** [comment]
Thanks for your quick response.
