### ISSUE TITLE
Support for runs-on ubuntu-24.04

### ISSUE THREAD

**Issue by mcwindy** [uraimo/run-on-arch-action#157]
Does this project now support running on ubuntu-24.04? Since [ubuntu24.04 is available](https://github.com/actions/runner-images/issues/9848) on github action.

**Comment by martin-g** [comment]
The runner image is used as a host for the containers provided/started by this action, so the link is not really related.
Please read the README. It explains how to use the action. See the docs and examples for `base_image` setting - it makes it possible to use any Docker image for the container.
