### ISSUE TITLE
armv7/aarch64 fail with bookworm and bullseye

### ISSUE THREAD

**Issue by substring** [uraimo/run-on-arch-action#158]
When starting the action, Docker fails with `no match for platform in manifest: not found` whereas buster still works ok.

Trying the new syntax forcing the platform works for aarch64 but fails on armv7 for bookworm and bullseye. In other words: 
  - :ok: `--platform=linux/armv7 arm32v7/debian:buster `
  - :red_circle: `--platform=linux/armv7 arm32v7/debian:bullseye`
  - :red_circle: `--platform=linux/armv7 arm32v7/debian:bookworm`
  - :ok: `--platform=linux/aarch64 arm64v8/debian:buster`
  - :ok: `--platform=linux/aarch64 arm64v8/debian:bullseye`
  - :ok: `--platform=linux/aarch64 arm64v8/debian:bookworm`

On a side note, not specifying arch and distro makes packages cache useless since all these "none-none" overlap eachother.

**Comment by uraimo** [comment]
Try `--platform=linux/arm/v7`, this should work.

**Comment by substring** [comment]
Thanks for the quick reply!

`arm/v7` seems to work.

I'm not using arch and dist because they just don't work, except for buster. But now, should I use `arm/v7` as arch instead of filling `base_image` as in my 1st message ?

**Comment by substring** [comment]
After reading https://github.com/uraimo/run-on-arch-action/issues/155#issuecomment-2425843608, I noticed I was still on v2.7.2. I've updated since, issue solved.
