### ISSUE TITLE
Failed to run command on aarch64

### ISSUE THREAD

**Issue by rodrigorodrigues** [uraimo/run-on-arch-action#35]
Hi,

I'm trying to run a command on `aarch64 architecture` but got the error below and I'm not quite sure what that means, maybe some missing configuration? The issue happens on line 84(mvn command)

Build failed = https://github.com/rodrigorodrigues/spring-native-crud-mongodb/runs/2117047728?check_suite_focus=true

Github Actions file = https://github.com/rodrigorodrigues/spring-native-crud-mongodb/blob/master/.github/workflows/spring-native.yml#L65-L84

Error
```
qemu-aarch64-static: Could not open '/lib/ld-linux-aarch64.so.1': No such file or directory
Error: Process completed with exit code 255.
``` 

Thanks

**Comment by uraimo** [comment]
Hi, you are inside the aarch64 emulated environment only for the step that's using run-on-action, for everything that comes after you go back to the standard github amd64 env.
In the workflow you linked, you have installed aarch64 java on the amd64 host, then run line 78 and 79 in the aarch64 env and then again launched maven in the amd64 environment.

What I recommend is to install java11-aarch64 manually in the setup section of run-on-arch and then launch mvn in the run section. For the last part you'll have to install docker in the setup section too, but I'm not really sure if it will work out of the box.
