### ISSUE TITLE
SSL certificate problem with armv6 using buster

### ISSUE THREAD

**Issue by patrickelectric** [uraimo/run-on-arch-action#36]
From: https://github.com/patrickelectric/mavlink-camera-manager/runs/2120968009?check_suite_focus=true#step:4:1420

**Comment by uraimo** [comment]
Try adding an `apt upgrade` after the update in your yml, this command is failing because the certificate cache is likely out of date (unexpected, but no idea when the docker image was last refreshed):

     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs

If even that doesn't work try also relinking the cache with `update-ca-certificates --fresh`.

**Comment by patrickelectric** [comment]
So I didi it in the end with:
```
apt update -y
apt install -y ca-certificates
update-ca-certificates --fresh
export SSL_CERT_DIR=/etc/ssl/certs
```

To force update and force the usage of the certificates, thanks!
