### ISSUE TITLE
The advanced example produces a warning

### ISSUE THREAD

**Issue by umonaca** [uraimo/run-on-arch-action#38]
The advanced example produces the following warning in the build step:

```
Warrning: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested.
```

Is it an intended behaviour?

**Comment by rettichschnidi** [comment]
Seems to be related to newer docker versions: https://github.com/balena-io-library/resin-rpi-raspbian/issues/104

**Comment by rnayabed** [comment]
Same problem. Cant get aarch64 to work at all

**Comment by rnayabed** [comment]
My problem was because I was trying to use sudo which apparently doesn't come with the aarch64 images

**Comment by rnayabed** [comment]
@uraimo why did you close this issue?

**Comment by uraimo** [comment]
@rnayabed that's an expected warning with no implication for the user. In your case, as you said: "I was trying to use sudo which apparently doesn't come with the aarch64 images". Issue closed.

**Comment by rnayabed** [comment]
> @rnayabed that's an expected warning with no implication for the user. In your case, as you said: "I was trying to use sudo which apparently doesn't come with the aarch64 images". Issue closed.

ah i see. actually my above comments were not related to the issue itself anyways.
