### ISSUE TITLE
Continue in another job?

### ISSUE THREAD

**Issue by radimkohout** [uraimo/run-on-arch-action#40]
I am using your action in my workflow to compile the Linux kernel. This takes longer than 6h limit of job in GitHub Actions. Is it somehow possible to use same Docker container on next job, and continue with compilation?

**Comment by uraimo** [comment]
Check out #34, other than adding all you can in the setup phase and caching the result of previous attempts (partial or full) can't think of any obvious way to try to reach the end of a long build. The docker container is only available in the context of the current job.

**Comment by radimkohout** [comment]
You can download linux kernel, add this config to it, and try it yourself 😀
https://gist.github.com/radimkohout/e59440d3a06a763d26e1ca43ce9dd258

**Comment by uraimo** [comment]
Don't worry, I have no trouble believing that 6h are not enough to build the kernel in an emulated environment :)
