### ISSUE TITLE
Switch from the Docker Registry to the Container Registry

### ISSUE THREAD

**Issue by sgallagher** [uraimo/run-on-arch-action#51]
Github no longer uses docker.pkg.github.com and is now using ghcr.io for container storage. As a result, all consumers of this action using the `GITHUB_TOKEN` option are broken.

https://docs.github.com/en/packages/working-with-a-github-packages-registry/migrating-to-the-container-registry-from-the-docker-registry

**Comment by uraimo** [comment]
Thanks for pointing this out, didn't know, fixed in 2.1.0.
