### ISSUE TITLE
release number in readme is not the recent one

### ISSUE THREAD

**Issue by rizsotto** [uraimo/run-on-arch-action#64]
Hi,

first and foremost, thanks for this wonderful tool. It really helps me to catch problems early on my project.

A short feedback I would like to give, to improve the user experience... I did copy-paste out one of the example from the `README.md` file. And simple added different architectures as the "Supported Platform" section of the same file suggest. The problem is, the example uses the `v2.0.5` label, which do not have all the images as the "Supported Platform" section lists.

I think this can be avoided in multiple ways.
- The easiest could be to use the latest `v2.1.1` in the examples.
- The more elegant can be to create a `v2` floating label. (This is what the official `actions/checkout@v2` does too.) This would make your action as `uraimo/run-on-arch-action@v2`.

What do you think?

**Comment by s-trinh** [comment]
> The more elegant can be to create a v2 floating label. (This is what the official actions/checkout@v2 does too.) This would make your action as uraimo/run-on-arch-action@v2

That's would be great!

**Comment by elijahr** [comment]
@rizsotto I love this idea. I'm not a maintainer, just a contributor, so I don't have the final say but I've gone ahead and opened a PR to add this functionality. Cheers!
