### ISSUE TITLE
How to increase memory/cpu dedicated to container?

### ISSUE THREAD

**Issue by ericdallo** [uraimo/run-on-arch-action#70]
I'm compiling something heavy on this action, I'd like to use all memory/cpu from github runner, how to achieve that?

**Comment by martin-g** [comment]
Why do you believe the Docker container started by the action uses less resources ?
Unless you specify some limits in your `dockerRunArgs` it must use all available resources.

**Comment by ericdallo** [comment]
Sorry for not clarrifying, I used this action for some time on [clojure-lsp](https://github.com/clojure-lsp/clojure-lsp/) to compile it to graalvm on aarch64, and the action take ~1h-15m while other builds take 10-15mins
https://github.com/clojure-lsp/clojure-lsp/actions/runs/3191211682/jobs/5207278718

**Comment by martin-g** [comment]
This action uses QEMU to emulate the target CPU architecture and QEMU is
known to be several times slower than native execution.

**Comment by ericdallo** [comment]
I see, so it's a QEMU limitation, maybe we should mention it somewhere on the readme?

**Comment by uraimo** [comment]
Here :) https://github.com/uraimo/run-on-arch-action#architecture-emulation
