### ISSUE TITLE
Document the fact that emulation is being used.

### ISSUE THREAD

**Issue by spookylukey** [uraimo/run-on-arch-action#71]
It might be really obvious to people who know how this works, but for someone just looking to run something on non-x86 arch it might not be. I had to dig quite a bit to confirm that emulation via QEmu was being used. This matters because it is going to have [big implications for performance](https://github.com/uraimo/run-on-arch-action/issues/4).

This could be as simple as changing the description to:

> A GitHub Action that executes commands on non-x86 CPU architecture (armv6, armv7, aarch64, s390x, ppc64le) **using emulation**.

**Comment by uraimo** [comment]
Makes sense.
